name: CI CD
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
        -   uses: actions/checkout@v2
        -   uses: addnab/docker-run-action@v3
            with:
                image: flaviobrassesco/lua-with-busted:latest
                options: -v ${{ github.workspace }}:/app
                run: cd app && busted test/main.lua